/**
 * Maps app registry icon names to Heroicons components.
 * Outline variants for default state, solid for active state.
 */
import {
  CalendarDaysIcon as CalendarDaysOutline,
  UsersIcon as UsersOutline,
  BanknotesIcon as BanknotesOutline,
  ReceiptPercentIcon as ReceiptPercentOutline,
  ArchiveBoxIcon as ArchiveBoxOutline,
  ShoppingCartIcon as ShoppingCartOutline,
  Cog8ToothIcon as Cog8ToothOutline,
  Squares2X2Icon as Squares2X2Outline,
  ClipboardDocumentCheckIcon as ClipboardDocCheckOutline,
  ArrowsRightLeftIcon as ArrowsRightLeftOutline,
  TagIcon as TagOutline,
  MapPinIcon as MapPinOutline,
  TruckIcon as TruckOutline,
  ClipboardDocumentListIcon as ClipboardDocListOutline,
  ArrowPathIcon as ArrowPathOutline,
  BuildingStorefrontIcon as BuildingStorefrontOutline,
  ChartBarIcon as ChartBarOutline,
  AcademicCapIcon as AcademicCapOutline,
  StarIcon as StarOutline,
  FolderIcon as FolderOutline,
  RectangleGroupIcon as RectangleGroupOutline,
  CurrencyEuroIcon as CurrencyEuroOutline,
  UserCircleIcon as UserCircleOutline,
  ClockIcon as ClockOutline,
  SunIcon as SunOutline,
  DocumentDuplicateIcon as DocumentDuplicateOutline,
  HomeIcon as HomeOutline,
  PlayCircleIcon as PlayCircleOutline,
  DocumentTextIcon as DocumentTextOutline,
  MinusCircleIcon as MinusCircleOutline,
  BuildingLibraryIcon as BuildingLibraryOutline,
  ArrowDownTrayIcon as ArrowDownTrayOutline,
  ArrowUpRightIcon as ArrowUpRightOutline,
  ArrowDownLeftIcon as ArrowDownLeftOutline,
  CreditCardIcon as CreditCardOutline,
  Cog6ToothIcon as Cog6ToothOutline,
  KeyIcon as KeyOutline,
  ServerIcon as ServerOutline,
  BellIcon as BellOutline,
  UserPlusIcon as UserPlusOutline,
} from '@heroicons/react/24/outline';

import {
  CalendarDaysIcon as CalendarDaysSolid,
  UsersIcon as UsersSolid,
  BanknotesIcon as BanknotesSolid,
  ReceiptPercentIcon as ReceiptPercentSolid,
  ArchiveBoxIcon as ArchiveBoxSolid,
  ShoppingCartIcon as ShoppingCartSolid,
  Cog8ToothIcon as Cog8ToothSolid,
  Squares2X2Icon as Squares2X2Solid,
  ClipboardDocumentCheckIcon as ClipboardDocCheckSolid,
  ArrowsRightLeftIcon as ArrowsRightLeftSolid,
  TagIcon as TagSolid,
  MapPinIcon as MapPinSolid,
  TruckIcon as TruckSolid,
  ClipboardDocumentListIcon as ClipboardDocListSolid,
  ArrowPathIcon as ArrowPathSolid,
  BuildingStorefrontIcon as BuildingStorefrontSolid,
  ChartBarIcon as ChartBarSolid,
  AcademicCapIcon as AcademicCapSolid,
  StarIcon as StarSolid,
  FolderIcon as FolderSolid,
  RectangleGroupIcon as RectangleGroupSolid,
  CurrencyEuroIcon as CurrencyEuroSolid,
  UserCircleIcon as UserCircleSolid,
  ClockIcon as ClockSolid,
  SunIcon as SunSolid,
  DocumentDuplicateIcon as DocumentDuplicateSolid,
  HomeIcon as HomeSolid,
  PlayCircleIcon as PlayCircleSolid,
  DocumentTextIcon as DocumentTextSolid,
  MinusCircleIcon as MinusCircleSolid,
  BuildingLibraryIcon as BuildingLibrarySolid,
  ArrowDownTrayIcon as ArrowDownTraySolid,
  ArrowUpRightIcon as ArrowUpRightSolid,
  ArrowDownLeftIcon as ArrowDownLeftSolid,
  CreditCardIcon as CreditCardSolid,
  Cog6ToothIcon as Cog6ToothSolid,
  KeyIcon as KeySolid,
  ServerIcon as ServerSolid,
  BellIcon as BellSolid,
  UserPlusIcon as UserPlusSolid,
} from '@heroicons/react/24/solid';

const outlineMap = {
  CalendarDaysIcon: CalendarDaysOutline,
  UsersIcon: UsersOutline,
  BanknotesIcon: BanknotesOutline,
  ReceiptPercentIcon: ReceiptPercentOutline,
  ArchiveBoxIcon: ArchiveBoxOutline,
  ShoppingCartIcon: ShoppingCartOutline,
  Cog8ToothIcon: Cog8ToothOutline,
  Squares2X2Icon: Squares2X2Outline,
  ClipboardDocumentCheckIcon: ClipboardDocCheckOutline,
  ArrowsRightLeftIcon: ArrowsRightLeftOutline,
  TagIcon: TagOutline,
  MapPinIcon: MapPinOutline,
  TruckIcon: TruckOutline,
  ClipboardDocumentListIcon: ClipboardDocListOutline,
  ArrowPathIcon: ArrowPathOutline,
  BuildingStorefrontIcon: BuildingStorefrontOutline,
  ChartBarIcon: ChartBarOutline,
  AcademicCapIcon: AcademicCapOutline,
  StarIcon: StarOutline,
  FolderIcon: FolderOutline,
  RectangleGroupIcon: RectangleGroupOutline,
  CurrencyEuroIcon: CurrencyEuroOutline,
  UserCircleIcon: UserCircleOutline,
  ClockIcon: ClockOutline,
  SunIcon: SunOutline,
  DocumentDuplicateIcon: DocumentDuplicateOutline,
  HomeIcon: HomeOutline,
  PlayCircleIcon: PlayCircleOutline,
  DocumentTextIcon: DocumentTextOutline,
  MinusCircleIcon: MinusCircleOutline,
  BuildingLibraryIcon: BuildingLibraryOutline,
  ArrowDownTrayIcon: ArrowDownTrayOutline,
  ArrowUpRightIcon: ArrowUpRightOutline,
  ArrowDownLeftIcon: ArrowDownLeftOutline,
  CreditCardIcon: CreditCardOutline,
  Cog6ToothIcon: Cog6ToothOutline,
  KeyIcon: KeyOutline,
  ServerIcon: ServerOutline,
  BellIcon: BellOutline,
  UserPlusIcon: UserPlusOutline,
};

const solidMap = {
  CalendarDaysIcon: CalendarDaysSolid,
  UsersIcon: UsersSolid,
  BanknotesIcon: BanknotesSolid,
  ReceiptPercentIcon: ReceiptPercentSolid,
  ArchiveBoxIcon: ArchiveBoxSolid,
  ShoppingCartIcon: ShoppingCartSolid,
  Cog8ToothIcon: Cog8ToothSolid,
  Squares2X2Icon: Squares2X2Solid,
  ClipboardDocumentCheckIcon: ClipboardDocCheckSolid,
  ArrowsRightLeftIcon: ArrowsRightLeftSolid,
  TagIcon: TagSolid,
  MapPinIcon: MapPinSolid,
  TruckIcon: TruckSolid,
  ClipboardDocumentListIcon: ClipboardDocListSolid,
  ArrowPathIcon: ArrowPathSolid,
  BuildingStorefrontIcon: BuildingStorefrontSolid,
  ChartBarIcon: ChartBarSolid,
  AcademicCapIcon: AcademicCapSolid,
  StarIcon: StarSolid,
  FolderIcon: FolderSolid,
  RectangleGroupIcon: RectangleGroupSolid,
  CurrencyEuroIcon: CurrencyEuroSolid,
  UserCircleIcon: UserCircleSolid,
  ClockIcon: ClockSolid,
  SunIcon: SunSolid,
  DocumentDuplicateIcon: DocumentDuplicateSolid,
  HomeIcon: HomeSolid,
  PlayCircleIcon: PlayCircleSolid,
  DocumentTextIcon: DocumentTextSolid,
  MinusCircleIcon: MinusCircleSolid,
  BuildingLibraryIcon: BuildingLibrarySolid,
  ArrowDownTrayIcon: ArrowDownTraySolid,
  ArrowUpRightIcon: ArrowUpRightSolid,
  ArrowDownLeftIcon: ArrowDownLeftSolid,
  CreditCardIcon: CreditCardSolid,
  Cog6ToothIcon: Cog6ToothSolid,
  KeyIcon: KeySolid,
  ServerIcon: ServerSolid,
  BellIcon: BellSolid,
  UserPlusIcon: UserPlusSolid,
};

export function getIconComponent(iconName, variant = 'outline') {
  const map = variant === 'solid' ? solidMap : outlineMap;
  return map[iconName] || null;
}
