/**
 * Maps app registry icon names to Heroicons components.
 * Outline variants for default state, solid for active state.
 */
import {
  CalendarDaysIcon as CalendarDaysOutline,
  UsersIcon as UsersOutline,
  BanknotesIcon as BanknotesOutline,
  ReceiptPercentIcon as ReceiptPercentOutline,
  ArchiveBoxIcon as ArchiveBoxOutline,
  ShoppingCartIcon as ShoppingCartOutline,
  Cog8ToothIcon as Cog8ToothOutline,
  Squares2X2Icon as Squares2X2Outline,
  ClipboardDocumentCheckIcon as ClipboardDocCheckOutline,
  ArrowsRightLeftIcon as ArrowsRightLeftOutline,
  TagIcon as TagOutline,
  MapPinIcon as MapPinOutline,
  TruckIcon as TruckOutline,
  ClipboardDocumentListIcon as ClipboardDocListOutline,
  ArrowPathIcon as ArrowPathOutline,
  BuildingStorefrontIcon as BuildingStorefrontOutline,
  ChartBarIcon as ChartBarOutline,
  AcademicCapIcon as AcademicCapOutline,
  StarIcon as StarOutline,
  FolderIcon as FolderOutline,
  RectangleGroupIcon as RectangleGroupOutline,
  CurrencyEuroIcon as CurrencyEuroOutline,
} from '@heroicons/react/24/outline';

import {
  CalendarDaysIcon as CalendarDaysSolid,
  UsersIcon as UsersSolid,
  BanknotesIcon as BanknotesSolid,
  ReceiptPercentIcon as ReceiptPercentSolid,
  ArchiveBoxIcon as ArchiveBoxSolid,
  ShoppingCartIcon as ShoppingCartSolid,
  Cog8ToothIcon as Cog8ToothSolid,
  Squares2X2Icon as Squares2X2Solid,
  ClipboardDocumentCheckIcon as ClipboardDocCheckSolid,
  ArrowsRightLeftIcon as ArrowsRightLeftSolid,
  TagIcon as TagSolid,
  MapPinIcon as MapPinSolid,
  TruckIcon as TruckSolid,
  ClipboardDocumentListIcon as ClipboardDocListSolid,
  ArrowPathIcon as ArrowPathSolid,
  BuildingStorefrontIcon as BuildingStorefrontSolid,
  ChartBarIcon as ChartBarSolid,
  AcademicCapIcon as AcademicCapSolid,
  StarIcon as StarSolid,
  FolderIcon as FolderSolid,
  RectangleGroupIcon as RectangleGroupSolid,
  CurrencyEuroIcon as CurrencyEuroSolid,
} from '@heroicons/react/24/solid';

const outlineMap = {
  CalendarDaysIcon: CalendarDaysOutline,
  UsersIcon: UsersOutline,
  BanknotesIcon: BanknotesOutline,
  ReceiptPercentIcon: ReceiptPercentOutline,
  ArchiveBoxIcon: ArchiveBoxOutline,
  ShoppingCartIcon: ShoppingCartOutline,
  Cog8ToothIcon: Cog8ToothOutline,
  Squares2X2Icon: Squares2X2Outline,
  ClipboardDocumentCheckIcon: ClipboardDocCheckOutline,
  ArrowsRightLeftIcon: ArrowsRightLeftOutline,
  TagIcon: TagOutline,
  MapPinIcon: MapPinOutline,
  TruckIcon: TruckOutline,
  ClipboardDocumentListIcon: ClipboardDocListOutline,
  ArrowPathIcon: ArrowPathOutline,
  BuildingStorefrontIcon: BuildingStorefrontOutline,
  ChartBarIcon: ChartBarOutline,
  AcademicCapIcon: AcademicCapOutline,
  StarIcon: StarOutline,
  FolderIcon: FolderOutline,
  RectangleGroupIcon: RectangleGroupOutline,
  CurrencyEuroIcon: CurrencyEuroOutline,
};

const solidMap = {
  CalendarDaysIcon: CalendarDaysSolid,
  UsersIcon: UsersSolid,
  BanknotesIcon: BanknotesSolid,
  ReceiptPercentIcon: ReceiptPercentSolid,
  ArchiveBoxIcon: ArchiveBoxSolid,
  ShoppingCartIcon: ShoppingCartSolid,
  Cog8ToothIcon: Cog8ToothSolid,
  Squares2X2Icon: Squares2X2Solid,
  ClipboardDocumentCheckIcon: ClipboardDocCheckSolid,
  ArrowsRightLeftIcon: ArrowsRightLeftSolid,
  TagIcon: TagSolid,
  MapPinIcon: MapPinSolid,
  TruckIcon: TruckSolid,
  ClipboardDocumentListIcon: ClipboardDocListSolid,
  ArrowPathIcon: ArrowPathSolid,
  BuildingStorefrontIcon: BuildingStorefrontSolid,
  ChartBarIcon: ChartBarSolid,
  AcademicCapIcon: AcademicCapSolid,
  StarIcon: StarSolid,
  FolderIcon: FolderSolid,
  RectangleGroupIcon: RectangleGroupSolid,
  CurrencyEuroIcon: CurrencyEuroSolid,
};

export function getIconComponent(iconName, variant = 'outline') {
  const map = variant === 'solid' ? solidMap : outlineMap;
  return map[iconName] || null;
}
